name: Deploy Cloud Function

on:
  push:
    branches:
      - main  # or your default branch name

env:
  FUNCTION_NAME: function-1   # Replace with your function name
  REGION: us-central1                  # Replace with your desired region
  PROJECT_ID: '360954874762'          # Your project ID is already correct here

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/360954874762/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: github-actions@360954874762.iam.gserviceaccount.com

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: python39  # or your preferred runtime
          region: ${{ env.REGION }}
          source_dir: .     # Directory containing function code
          entry_point: hello_gcs  # Replace with your function's entry point