name: Deploy Cloud Function
on:
  push:
    branches:
      - main

env:
  FUNCTION_NAME: function-1
  REGION: us-central1
  PROJECT_ID: '360954874762'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/360954874762/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'
          service_account: github-actions@solid-future-422303-e8.iam.gserviceaccount.com
      
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloud-functions@v3'
        timeout-minutes: 10
        with:
          name: 'function-1'
          runtime: 'python39'